uktrade/pg-sync-roles

README.md, pg_sync_roles.py, test_pg_sync_roles.py
Having the "pg_" bit in the function name felt a bit redundant/overly verbose somehow
=> feat: rename function from pg_sync_roles to sync_roles

pg_sync_roles.py
And move the splitting out of the transaction, just under the principle that the shorter a transaction/less in it the better. Very very slightly from a performance point of view, but also for clarity.
=> refactor: group splitting grants by type

README.md
The sync_roles function does its own transaction management - it'll fail if already in a transaction.
=> docs: use connect rather than begin

pg_sync_roles.py, pyproject.toml, test_pg_sync_roles.py
As the comment suggests, elastic-apm seems to wrap connections which fails sql.SQL with
> "argument 1 must be psycopg2.extensions.connection, not PGConnectionProxy"
So we unwrap before passing to as_string.
=> feat: support wrapped connections

test_pg_sync_roles.py
A few cases where missed when we moved to testing on a database re-created for every test.
=> tests: test on the per-test database

test_pg_sync_roles.py
To make them more isolated from each other
=> tests: ensure to drop role between tests

README.md
I didn't know about pg_shdepend: I'm hoping that this can be used to find all the objects that the role has permissions or ownership on, and in a much more efficient way.
=> docs: simpler API without explicit revoking

pg_sync_roles.py, test_pg_sync_roles.py
This gives options for the future - allowing clearer "per just the connected database" permission changes, leaving permissions in other database alone.
=> feat: ensure role names have the current database oid in them

pg_sync_roles.py
To make sure that we don't try to re-create a schema if multiple clients are both creating the same schema.
=> feat: little bit of race condition avoidance, especially when creating schemas

pg_sync_roles.py, test_pg_sync_roles.py
This hopefully completes the revocation of all ACL permissions from pg_class, so all table-like objects.
=> feat: revoke permissions from sequences

pg_sync_roles.py
By removing the cast to ::regrole in this part of the query, it avoids a full table scan on pg_authid and shaves a few milliseconds from querying permissions. On a fairly complex database this leaves finding existing permissions of a role at around 8ms.
=> perf: faster check on existing permissions

pg_sync_roles.py
Making it so variables...
- end in `_to_create` if there for something to be created
- end in `_to_grant` if there for something to be granted
- end in `_to_revoke` if there is something to be revoked.
Also uses data classes internally a touch more
=> refactor: more consistent naming and usage of data classes

pg_sync_roles.py
Not entirely sure why tests were passing - suspect we just didn't have enough tables/namespaces to make the query return incorrect results
=> fix: query fetching table select roles

pg_sync_roles.py, test_pg_sync_roles.py
The main user in RDS is _not_ a superuser, and so we should make sure to work as superuser.
The only thing that's different is that to grant ownership of a role, then the current user has to be a member of that role
=> feat: work not as superuser - as in RDS

pg_sync_roles.py, test_pg_sync_roles.py
It more appropriate to use CURRENT_USER - this is the user _after_ any SET ROLE has been performed, and the one used for permissions checking.
=> feat: use CURRENT_USER everywhere

test_pg_sync_roles.py
I suspect I accidentally committed a change to 4
=> tests: restore number of calls in some tests to 4000

pg_sync_roles.py, test_pg_sync_roles.py
When objects are first created, their ACL is null (assuming no default ACL has been set otherwise via ALTER DEFAULT PRIVILEGES). In this case, the owner of the object in question has privileges corresponding to acldefault. So, when listing existing privileges we need to consult acldefault.
=> feat: handle null ACL when objects are created

README.md, pg_sync_roles.py, test_pg_sync_roles.py
pg-sync-roles doesn't yet have the ability to handle all use cases, and specifically certain situations of "team schemas" such as those in Data Workspace, where many users should have access to everything in a schema, even ones created in the future, after any call to sync_roles. Specifically, the sync_roles function would revoke access to tables in team schemas.
To work around this, this change adds the ability to ignore all objects in certain schemas, and so not revoke access to them.
=> feat: preserve privileges in team schemas

pg_sync_roles.py, test_pg_sync_roles.py
This change allow the grants on objects even if the current user is not the owner of the object. It does this by granting itself the owner role for any object if necessary.
=> fix: allow grant on schemas even if not owner

README.md, pg_sync_roles.py, test_pg_sync_roles.py
This I think has revealed some oddities when managing objects in schemas on which the syncing user doesn't have USAGE permission, which is revoked automatically when a schema's ownership is transferred to another user. Specifically, the syncing user then can't even see tables in the schema.
The best-effort change work around here is to grant itself the owner role of the schemas to try to get USAGE on them.
I am starting to suspect that ownership of schemas is a bit tricky to be delegated. Granting USAGE and CREATE is probably the way to go to allow roles to create things in them.
=> feat: revoke direct privileges on schemas

README.md, pg_sync_roles.py, test_pg_sync_roles.py
This adds the function drop_unused_roles to clear up unused roles. Should only really need to be called on systems that have a lot of table churn.
=> feat: add function to drop unused roles

pg_sync_roles.py
This changes one of the internal functions to use the variable passed to it, rather than the one in the surrounding scope.
It shouldn't change any functionality, the only use of the variable is to cast it to a bool, and the variables are always the same in terms of their truthyness.
=> refactor: use correct variable name in function

pg_sync_roles.py, test_pg_sync_roles.py
This fixes an issue where if the only change is the addition of a direct table permission, the permission wouldn't be granted, because the sync_roles function would incorrectly identifty there is nothing to do.
If there were other changes to be made, then permissions would be still be granted correctly.
=> fix: incorrectly not granting when only a direct table change

.github/workflows/test.yaml, README.md, pyproject.toml
This is slightly complicated because SQLAlchemy versions between 2.0.0 and 2.0.30 don't work on Python 3.13
=> ci: test on more Python versions

README.md, pg_sync_roles.py, test_pg_sync_roles.py
This adds a direct mode for the schema create permissions, which can be used to reduce the number of role memberships in a complex system.
=> feat: direct mode for schema create permission

pg_sync_roles.py, test_pg_sync_roles.py
TableSelect grants were being incorrectly filtered out when SchemeUsage was _not_ included in the grant list of the current role.
=> fix: SELECT incorrectly not being granted when USAGE is via another role

pg_sync_roles.py
This removes re-checking if tables/schemas/database exist after obtaining lock.
This might technically very slightly increase the chance of errors if say a schema is removed during the run of sync_roles, but the lock is not for wrapping the removal of tables/schemas(/database...), and so we are already vulnerable to that in various ways I suspect. I am pro to think about how to sort that properly later, or leave that as out of scope and a possible risk that calling code has to deal with.
=> perf: remove unnecessary queries after obtaining lock

README.md, pg_sync_roles.py, test_pg_sync_roles.py
This fixes behaviours around the Login grant, and specifically:
- When valid_until is None, no errors are raised and in the database the role can login until 'infinity'
- When no password is set via Login, then changes to valid_until are correctly applied (and existing password is preserved as before this change)
This is suspected to fix the second issue in https://github.com/uktrade/pg-sync-roles/issues/143
=> fix: login behaviours when valid_until is None and no password

pg_sync_roles.py
Prevent the login password from being logged on a Login() grant
=> fix: remove login password logging
