uktrade/pg-sync-roles

.github/workflows/test.yaml, start-services.sh, stop-services.sh
Setting up the GitHub actions for various postgreSQL and python versions and running a simple test to check python returns True
=> feat: setup github actions

pg_sync_roles.py
Didn't wait for tests to pass on previous PR...
=> fix: broken granting of connect

README.md, pg_sync_roles.py
This is for complex situations where not all changes can be done via pg-sync-roles.
Suspect this might also be helpful in tests down the line to test if syncing gets blocked or not.
=> feat: make lock key customisable and lightly document it

pg_sync_roles.py
I think just a regular isinstance is fine here
=> refactor: remove unnecessary function

pg_sync_roles.py
For clarity and a very minor performance benefit
=> refactor: move validation out from starting transaction

pg_sync_roles.py
Hoping to avoid the number of types of things the code works with for overal clarity/simpler mental modal of the code
=> refactor: work more with tuples of the database objects

pg_sync_roles.py
Hopefully fewer steps and a better foundation for other grant types
=> refactor: move more logic to SQL

pg_sync_roles.py, test_pg_sync_roles.py
This creates the RoleMemberhip grant type that is (lightly) documented already in the README that grants the main role membership of another role (and creates that role if it does not exist).
=> feat: create RoleMembership grant type

README.md
Maybe down the line we should, but I think for now, let's just do what's helpful to us
=> docs: simpler API - don't allow customisation of creation

pg_sync_roles.py, test_pg_sync_roles.py
This adds the schema ownership data class that is already documented in the
README that gives roles ownership of a particular schema. To keep it simple,
when revoking it grants ownership of the schema to the session user connecting
into the database.
=> feat: schema ownerships

pg_sync_roles.py
Am hoping that this is a small step towards a reduction of duplication and lots of "per grant type" code
=> refactor: move more code to existing permissions sql

pg_sync_roles.py
Hoping this is a reasonable route to duplication being reduced (and keeping things efficient, SQL-wise)
=> refactor: move existing permissions into sql

pg_sync_roles.py
And a stepping stone towards a different/more flexible API
=> refactor: reduce duplication

pg_sync_roles.py
Hopefully a stepping stone to a more general/flexible API
=> refactor: more general internal functions

pg_sync_roles.py, test_pg_sync_roles.py
To control the permissions on an object in PostgreSQL, the role doing the control needs to be owner on the object (or at least in PostgreSQL 16, be able to SET ROLE to the role that's the owner).
This change makes the syncing user temporarily the owner of tables when we REVOKE on them in order to do this.
=> fix: ensure can revoke permissions when not owner

pg_sync_roles.py
Having them upper case was a find/replace error
=> style: make local variables lower case

pg_sync_roles.py
This should allow a touch more type safety later, as we as (hopefully) easier refactoring.
=> refactor: privileges in enum

pg_sync_roles.py, test_pg_sync_roles.py
In order to GRANT the USAGE, the CURRENT_USER has to be granted the owner, so we always grant the owner to the CURRENT_USER. Suspect we'll need this for other things as well because in general lots of things will be owned by the role being managed.
=> fix: allow both usage and ownership to be specified

pg_sync_roles.py, test_pg_sync_roles.py
It should be possible for sync_roles to run fine on things that don't exist (this is current Data Workspace Frontend behaviour). There is some code in pg-sync-roles already to handle this case, but it wasn't properly wired up.
=> fix: don't fail if tables don't exist

README.md, pg_sync_roles.py, pytest.ini, test_pg_sync_roles.py
This should allow users to create tables (and other objects) in schemas. This is expected to be used in the Data Workspace Frontend at https://github.com/uktrade/data-workspace-frontend
=> feat: SchemaCreate grant type

README.md
So the information isn't lost so future developers are more aware of why certain things have been done.
=> docs: add design decisions

README.md, pg_sync_roles.py, test_pg_sync_roles.py
This adds the ability to _bypass_ the intermediate role system that pg-sync-roles was created with. This is to reduce the numbers of roles that users are granted.
While the intermediate role system addresses some issues ("row is too big" errors with high numbers of users granted access to tables), it now seems to have introduced another issue. For users with high numbers of roles granted, they can take a long time, > 90 seconds, to connect to the database.
In our usage of pg-sync-roles, all access to tables is not granted on an individual basis, but a large proportion is granted based on a membership of a low number of real-world groups that the users are members of. So we can make our own intermediate database roles that match these groups, make the users members of these roles, and give …
=> Allow permissions on an object to be granted to a role directly

README.md
Did explore doing this as a MermaidJS flow chart... but it was really big and it seemed worse than just a list.
=> docs: internal flow

test_pg_sync_roles.py
Not the most important thing in the world, but the previous pattern was stopping getting to 100% coverage in the test itself
=> test: refactor for higher code coverage metric

.github/workflows/test.yaml
I misunderstood how "include" works when there is a matrix. I thought it would "auto expand" all the matrix variables, but it doesn't.
=> ci: fix testing more Python versions

test_pg_sync_roles.py
This adds more tests around valid_until (should really have done these in the previous change that allowed valid_until to be None)
=> test: add valid_until tests on Login

README.md, pg_sync_roles.py, test_pg_sync_roles.py
Added option to grant TableOwnership with tests included.
=> feat: add table ownership permissions
